import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { CardsProvider } from "@/contexts/card-context";
import { MatchModal } from "@/components/modals/match-modal";
import { FinishModal } from "@/components/modals/finish-modal";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <CardsProvider>
          <MatchModal/>
          <FinishModal/>
          {children}
        </CardsProvider>
      </body>
    </html>
  );
}
